/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebComponentBusinessCard {
        "emailProfile": string;
        "phoneProfile": string;
        "webUrl": string;
    }
    interface WebComponentHello {
        "firstName": string;
        "websiteUrl": string;
    }
    interface WebCountriesFinder {
        "keyword": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebComponentBusinessCardElement extends Components.WebComponentBusinessCard, HTMLStencilElement {
    }
    var HTMLWebComponentBusinessCardElement: {
        prototype: HTMLWebComponentBusinessCardElement;
        new (): HTMLWebComponentBusinessCardElement;
    };
    interface HTMLWebComponentHelloElement extends Components.WebComponentHello, HTMLStencilElement {
    }
    var HTMLWebComponentHelloElement: {
        prototype: HTMLWebComponentHelloElement;
        new (): HTMLWebComponentHelloElement;
    };
    interface HTMLWebCountriesFinderElement extends Components.WebCountriesFinder, HTMLStencilElement {
    }
    var HTMLWebCountriesFinderElement: {
        prototype: HTMLWebCountriesFinderElement;
        new (): HTMLWebCountriesFinderElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "web-component-business-card": HTMLWebComponentBusinessCardElement;
        "web-component-hello": HTMLWebComponentHelloElement;
        "web-countries-finder": HTMLWebCountriesFinderElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebComponentBusinessCard {
        "emailProfile"?: string;
        "phoneProfile"?: string;
        "webUrl"?: string;
    }
    interface WebComponentHello {
        "firstName"?: string;
        "websiteUrl"?: string;
    }
    interface WebCountriesFinder {
        "keyword"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "web-component-business-card": WebComponentBusinessCard;
        "web-component-hello": WebComponentHello;
        "web-countries-finder": WebCountriesFinder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-component-business-card": LocalJSX.WebComponentBusinessCard & JSXBase.HTMLAttributes<HTMLWebComponentBusinessCardElement>;
            "web-component-hello": LocalJSX.WebComponentHello & JSXBase.HTMLAttributes<HTMLWebComponentHelloElement>;
            "web-countries-finder": LocalJSX.WebCountriesFinder & JSXBase.HTMLAttributes<HTMLWebCountriesFinderElement>;
        }
    }
}
